-- Run this in your Supabase SQL Editor AFTER planning-schema-detail.sql.
-- Imports planned quantities from "LD (MB) Purchase Detail.xlsx" (Ladies
-- Footwears, MB section, Sep'26-Feb'27 plan) into order_plan_details.
-- Only inserts/updates rows for the (department, category, sub_category,
-- heels) combinations listed below — every other order_plan_details row,
-- every order_plans row, and every shoe_categorizations entry is untouched.
-- Safe to re-run: existing rows are matched on the unique key and their
-- planned_qty is overwritten with the value below, nothing is duplicated.

insert into public.order_plan_details (department, category, sub_category, heels, planned_qty)
values
  ('Ladies Footwears', 'Ballerina', 'Casualwear', 'Flat', 21032),
  ('Ladies Footwears', 'Ballerina', 'Partywear', 'Flat', 1088),
  ('Ladies Footwears', 'Boots', 'Casualwear', 'Flat', 773),
  ('Ladies Footwears', 'Boots', 'Casualwear', 'High Heel', 4390),
  ('Ladies Footwears', 'Boots', 'Casualwear', 'High Platform', 16),
  ('Ladies Footwears', 'Boots', 'Casualwear', 'High Wedge', 35),
  ('Ladies Footwears', 'Boots', 'Casualwear', 'Medium Heel', 5194),
  ('Ladies Footwears', 'Boots', 'Casualwear', 'Short Heel', 3716),
  ('Ladies Footwears', 'Boots', 'Casualwear', 'Short Wedge', 437),
  ('Ladies Footwears', 'Bridalshoes', 'Partywear', 'High Platform', 1004),
  ('Ladies Footwears', 'Bridalshoes', 'Partywear', 'Medium Platform', 200),
  ('Ladies Footwears', 'Bridalshoes', 'Partywear', 'Short Platform', 2676),
  ('Ladies Footwears', 'Comfortwalker', 'Casualwear', 'Flat', 7315),
  ('Ladies Footwears', 'Comfortwalker', 'Casualwear', 'Medium Heel', 430),
  ('Ladies Footwears', 'Comfortwalker', 'Casualwear', 'Short Platform', 1709),
  ('Ladies Footwears', 'Comfortwalker', 'Casualwear', 'Short Wedge', 375),
  ('Ladies Footwears', 'Comfortwalker', 'Partywear', 'Flat', 611),
  ('Ladies Footwears', 'Comfyhomewear', 'Casualwear', 'Flat', 6931),
  ('Ladies Footwears', 'Comfyhomewear', 'Casualwear', 'Short Platform', 29),
  ('Ladies Footwears', 'Crocs', 'Casualwear', 'Flat', 800),
  ('Ladies Footwears', 'Floater', 'Casualwear', 'Flat', 711),
  ('Ladies Footwears', 'Floater', 'Casualwear', 'Short Platform', 49),
  ('Ladies Footwears', 'Jutti', 'Casualwear', 'Flat', 1642),
  ('Ladies Footwears', 'Jutti', 'Partywear', 'Flat', 26758),
  ('Ladies Footwears', 'Loafer', 'Casualwear', 'Flat', 13041),
  ('Ladies Footwears', 'Loafer', 'Casualwear', 'Medium Heel', 3495),
  ('Ladies Footwears', 'Loafer', 'Casualwear', 'Medium Platform', 14),
  ('Ladies Footwears', 'Loafer', 'Casualwear', 'Short Heel', 278),
  ('Ladies Footwears', 'Loafer', 'Casualwear', 'Short Platform', 22),
  ('Ladies Footwears', 'Loafer', 'Casualwear', 'Short Wedge', 2711),
  ('Ladies Footwears', 'Mules', 'Casualwear', 'Flat', 1325),
  ('Ladies Footwears', 'Mules', 'Casualwear', 'High Heel', 3262),
  ('Ladies Footwears', 'Mules', 'Casualwear', 'Medium Heel', 9894),
  ('Ladies Footwears', 'Mules', 'Casualwear', 'Medium Platform', 182),
  ('Ladies Footwears', 'Mules', 'Casualwear', 'Short Heel', 2933),
  ('Ladies Footwears', 'Mules', 'Casualwear', 'Short Platform', 619),
  ('Ladies Footwears', 'Mules', 'Casualwear', 'Short Wedge', 904),
  ('Ladies Footwears', 'Mules', 'Partywear', 'Flat', 1195),
  ('Ladies Footwears', 'Mules', 'Partywear', 'High Heel', 5472),
  ('Ladies Footwears', 'Mules', 'Partywear', 'Medium Heel', 7515),
  ('Ladies Footwears', 'Mules', 'Partywear', 'Medium Platform', 139),
  ('Ladies Footwears', 'Mules', 'Partywear', 'Short Heel', 1481),
  ('Ladies Footwears', 'Pumps', 'Casualwear', 'High Heel', 9432),
  ('Ladies Footwears', 'Pumps', 'Casualwear', 'Medium Heel', 14610),
  ('Ladies Footwears', 'Pumps', 'Casualwear', 'Short Heel', 21085),
  ('Ladies Footwears', 'Pumps', 'Casualwear', 'Short Wedge', 2037),
  ('Ladies Footwears', 'Pumps', 'Partywear', 'High Heel', 4709),
  ('Ladies Footwears', 'Pumps', 'Partywear', 'Medium Heel', 1858),
  ('Ladies Footwears', 'Pumps', 'Partywear', 'Short Heel', 195),
  ('Ladies Footwears', 'Sandal', 'Casualwear', 'Flat', 6374),
  ('Ladies Footwears', 'Sandal', 'Casualwear', 'High Heel', 4757),
  ('Ladies Footwears', 'Sandal', 'Casualwear', 'High Platform', 94),
  ('Ladies Footwears', 'Sandal', 'Casualwear', 'Medium Heel', 5297),
  ('Ladies Footwears', 'Sandal', 'Casualwear', 'Medium Platform', 917),
  ('Ladies Footwears', 'Sandal', 'Casualwear', 'Short Heel', 1104),
  ('Ladies Footwears', 'Sandal', 'Casualwear', 'Short Platform', 214),
  ('Ladies Footwears', 'Sandal', 'Casualwear', 'Short Wedge', 511),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'Flat', 775),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'High Heel', 15274),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'High Platform', 653),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'High Wedge', 256),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'Medium Heel', 9989),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'Medium Platform', 820),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'Short Heel', 2070),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'Short Platform', 354),
  ('Ladies Footwears', 'Sandal', 'Partywear', 'Short Wedge', 302),
  ('Ladies Footwears', 'Slipper', 'Casualwear', 'Flat', 15609),
  ('Ladies Footwears', 'Slipper', 'Casualwear', 'High Heel', 3427),
  ('Ladies Footwears', 'Slipper', 'Casualwear', 'Medium Heel', 9381),
  ('Ladies Footwears', 'Slipper', 'Casualwear', 'Medium Platform', 4951),
  ('Ladies Footwears', 'Slipper', 'Casualwear', 'Short Heel', 116),
  ('Ladies Footwears', 'Slipper', 'Casualwear', 'Short Platform', 288),
  ('Ladies Footwears', 'Slipper', 'Casualwear', 'Short Wedge', 462),
  ('Ladies Footwears', 'Slipper', 'Partywear', 'Flat', 6344),
  ('Ladies Footwears', 'Slipper', 'Partywear', 'High Heel', 9337),
  ('Ladies Footwears', 'Slipper', 'Partywear', 'High Platform', 59),
  ('Ladies Footwears', 'Slipper', 'Partywear', 'Medium Heel', 45862),
  ('Ladies Footwears', 'Slipper', 'Partywear', 'Medium Platform', 11989),
  ('Ladies Footwears', 'Slipper', 'Partywear', 'Short Heel', 327),
  ('Ladies Footwears', 'Slipper', 'Partywear', 'Short Wedge', 364),
  ('Ladies Footwears', 'Sneaker', 'Casualwear', 'Flat', 11616),
  ('Ladies Footwears', 'Sneaker', 'Partywear', 'Flat', 631),
  ('Ladies Footwears', 'Sneaker', 'Partywear', 'Short Platform', 33),
  ('Ladies Footwears', 'Sportshoes', 'Casualwear', 'Flat', 5300),
  ('Ladies Footwears', 'Sportshoes', 'Casualwear', 'Medium Heel', 9),
  ('Ladies Footwears', 'Sportshoes', 'Casualwear', 'Short Platform', 211),
  ('Ladies Footwears', 'Vshape', 'Casualwear', 'Flat', 9055),
  ('Ladies Footwears', 'Vshape', 'Casualwear', 'High Heel', 82),
  ('Ladies Footwears', 'Vshape', 'Casualwear', 'Medium Heel', 1295),
  ('Ladies Footwears', 'Vshape', 'Casualwear', 'Medium Platform', 2827),
  ('Ladies Footwears', 'Vshape', 'Casualwear', 'Medium Wedge', 39),
  ('Ladies Footwears', 'Vshape', 'Casualwear', 'Short Heel', 4),
  ('Ladies Footwears', 'Vshape', 'Casualwear', 'Short Platform', 163),
  ('Ladies Footwears', 'Vshape', 'Casualwear', 'Short Wedge', 844),
  ('Ladies Footwears', 'Vshape', 'Partywear', 'Flat', 5697),
  ('Ladies Footwears', 'Vshape', 'Partywear', 'Medium Heel', 3980),
  ('Ladies Footwears', 'Vshape', 'Partywear', 'Medium Platform', 1679),
  ('Ladies Footwears', 'Vshape', 'Partywear', 'Short Heel', 77),
  ('Ladies Footwears', 'Vshape', 'Partywear', 'Short Platform', 9),
  ('Ladies Footwears', 'Vshape', 'Partywear', 'Short Wedge', 1852)
on conflict (department, category, sub_category, heels)
do update set planned_qty = excluded.planned_qty;
